# ğŸ‘‹ Hey there! I'm Zaynab
ğŸ‘½[Linkedin](https://www.linkedin.com/in/zaynab-soyokulova/)  / ğŸ“§ [Gmail](https://mail.google.com/mail/u/soyoqulova@gmail.com) / ğŸ’½ [Discord](https://discordapp.com/users/1052815197422751805) / 
ğŸ•µï¸â€â™€ï¸ [Github](https://github.com/aurorazeyn) / ğŸ›° [Telegram](https://t.me/aurorazeyn) 

## ğŸ‘©ğŸ»â€ğŸ’» About Me
- ğŸŒ±  Born and Raised in Jizakh
- ğŸ¢  BSc'25 | BIS| Westminster International University in Tashkent (WIUT)
-  ğŸ“  Based in Tashkent
- ğŸ’¼  Learning and Working on an exciting project for an Eco club of WIUT as a Junior Researcher and Data Enthuasist
- ğŸ”­  Currently deepening in Data 
- ğŸ§   Enthusiast in exploring the intersections of Tech, Computational Neuroscience and Consiousness Business
- ğŸ§˜ğŸ»â€â™€ï¸  Enjoy doing yoga and Walking around City bring me peace
- âœï¸  Constructive writing helps me to think clearly [a piece of writings](https://www.linkedin.com/pulse/unconscious-becomes-conscious-zaynab-soyokulova/)

## ğŸ•µğŸ»â€â™€ï¸ Work Experience
- Librarian | Team Language Center | 2016-2018
- Translator | Khan Academy Uzbek  |  05/2019-09/2019
  | Translated different subjects into Uzbek language
- Graphic Designer | Crave | [TBC-Ornaments](https://tbc-ornaments.uz/) project | 06/2021-07/2023
  | Eye to Details, Created Mockups, Vectorized illustrations
- Entry-level UX/UI Designer | [Argue](https://www.figma.com/file/2hwgObRTqmrystdDsjP83J/ARG?type=design&node-id=2316%3A30665&mode=design&t=cD3eNpGMbeYvzFHo-1) project, Brazilian Startup | Freelancing | 2021-2022
- Graphic Designer | Agro Finans Lizing | [Portfolio](https://www.notion.so/aurorazeyn/Portfolio-87ca5e1282f74d9987a571fd5983c50a?pvs=4) | 08/2022-09/2023
| Created Mockups, Designed Calendars | Notebooks | Presentations | SM Posts 
- Product Manager | WeInvest Capital - NY, USA | Online internship | 04/2023-07/2023
- Market | User Research, Conducted user interviews and surveys, Customer Development, Market research, Competitors analysis
- UX/UI Designer | Upwork | [Inkleaf](https://www.figma.com/file/mgyughXN9SdhDgeXVdgEFV/InkLeaf?type=design&node-id=0%3A1&mode=design&t=l76sLjBe1oWceYqJ-1) | Timely project


## ğŸ›  Hard Skills
- HTML, CSS, JavaScript, Python, SQL - Basics
- Excel - Basics
- UX | UI design concepts - Strong
- Project Management - Basics
- Notion, Trello, Photoshop , Illustrator, Figma - Advanced user

## ğŸŒ¼ Soft Skills
- Communication
- Problem-solving
- Analytical Thinking
- Critical Thinking
-  Planning / Research
- Adaptability
- Leadership
- Emotional Intelligence
- Creativity
- Resilience

## ğŸ– Achievements
Republican Forum of Young Artists | 01/2018
- Organized Republican Forum of Young Artists with a Team under Youth Officials Organization
- Managed a group of participants (A winner group)
  [photo](https://scontent.ftas11-1.fna.fbcdn.net/v/t1.18169-9/22365208_944682859021582_5429686783486458251_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=5f2048&_nc_ohc=ZRtH8YZJOm8AX8LKRgP&_nc_ht=scontent.ftas11-1.fna&oh=00_AfDp3V0PlzwuA_XqKF-DcBUXAbC9e-_bSGl-hG7AmmA4yg&oe=661D3963)

GPT Hackaton | [Certificate](https://media.licdn.com/dms/image/D4D2DAQGG56PYmRiuMQ/profile-treasury-image-shrink_800_800/0/1709739140105?e=1711213200&v=beta&t=w_vygLpT8jaI4fPjjxMsI-zzlrl0DwEt4zMv_oHbF9U) |02/2013
- We developed with a team of two people, a consultancy app called "Hypersono" which has features of
give a helping hand to young people who
- seek career advice
- financial advice
- health advice
- education advice
by integrating the academic and self-development books to produce GPT prompts that command in audio, video and text format.
The problem was the young people who reside in villages and other edges of the regions where there are no available helpful sources that they can access

Problem Solving International Hackathon 2024 | [Certificate](https://media.licdn.com/dms/image/D4D2DAQF4jOrtQ9VHmw/profile-treasury-document-cover-images_1280/0/1709738960973?e=1711213200&v=beta&t=pVpBD2zZ0bux9ZBl4bpazMOGFQg5IRtd_D9RUw0dYU0) | 02/2024
- We participated with our team and tested our
- Logical thinking
- Math
- Programming skills

## ğŸŒ‹ Volunteering
Young Leader Development Project (YLDP) | 2017-2018
 - Participated in organizing the events in YLDP
 - Volunteered in the "International Youth Summit - 2017

Women in Techmakers | 2022-Present
- Brainstromed the events with a team
- Volunteered in the organized events

IT Community of Uzbekistan + Women in Tech | 2023-Present
- Participated as a graphic designer
- Designed stickers, posts, gift packages etc.
- Brainstormed tech ideas with a team
- Organized GPT Hackatons and Organizing future upcoming events 

## :electron: Languages
- Uzbek - Native
- Russian - Intermediate
- English - Advanced
